---
name: Nightly - tfsec Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '33 */12 * * *'

jobs:
  tfsec:
    name: Run tfsec Security Scan Report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run tfsec scan with SARIF output
        uses: aquasecurity/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif
          full_repo_scan: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
