---
name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_terraform:
    name: Test Terraform
    runs-on: ubuntu-latest

    steps:
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Terraform version
        id: version
        run: terraform version

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -diff -recursive

  test_linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      # Run Linter against code base
      - name: Run linter against all changed files
        uses: super-linter/super-linter/slim@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_TERRAFORM_TERRASCAN: false
