---
name: Test
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test_opentofu:
    name: Test OpenTofu
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: OpenTofu - Setup OpenTofu
        uses: opentofu/setup-opentofu@847eaa4afeb791b06daa46e8eafa8b1b68d7cfb4 # v2.0.1

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: OpenTofu version
        id: version
        run: tofu version

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check -diff -recursive

  test_unicode:
    name: Invisible Unicode Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Check for invisible Unicode characters
        run: bash .github/scripts/check_unicode.sh

  test_linter:
    name: Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
          persist-credentials: false

      # Run Linter against code base
      - name: Run linter against all changed files
        uses: super-linter/super-linter/slim@9e863354e3ff62e0727d37183162c4a88873df41 # v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_GIT_COMMITLINT: false
          SAVE_SUPER_LINTER_SUMMARY: true
